server:
  port: 8080
  servlet:
    context-path: /santanderDevWeek

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado durante o evento Santander Dev Week como aquecimento para o Bootcamp DIO - Santander Dev Full Stack